In [ ]:
# Практическое задания #1
* Попробуйте получить данные о манометрах, поверенных в ЦАГИ имени Н.Е. Жуковского
* Проверьте есть ли в МАИ поверенные расходомеры
* Проверьте свой домашний счетчик воды (горячей или холодной) на наличие поверки, если конечно счетчик у вас установлен &#x1F600; и он был поверен после 24.09.2020 года (именно с этой даты все организации обязаны передавать данные о поверке в единую систему).

Все данные по п.1/2 обработайте и сведите в Pandas Dataframe в формат удобный для датасета по оценке запросов на поверку средств измерения

In [ ]:
#импортируем необходимые библеотеки 
import pandas as pd
import requests

In [ ]:
#создаем поиска 
def get_result_org(o_title, m_title, ):
    keys = {'regkey': 'd37e5f9c2df49556a580b1c3dc8dcc7a',
        'org_title':o_title,
        'mitypeTitle':m_title,
        'export_type': '2'}
    r = requests.get('http://731163-cj72200.tmweb.ru/vri/', params=keys)
    df = pd.DataFrame(r.json())
    return df

SyntaxError: invalid syntax (2047512785.py, line 6)

In [ ]:
#Получаем данные по  цаги 
df_tsagi=get_result_org('ЦАГИ','манометр')
display(df_tsagi)

,id,vri_id,mi_number,mi_modification,mi_manufactureYear,mi_signCipher,mi_Owner_name,org_title,fsa_ral_regNumbers_regNumber,mitypeNumber,...,vriType,result_docnum,result_doc_type,additional_info,means_npe,means_uve,means_mieta,means_ses,means_mis,means_reagent
0,1,1173224226,01-К,,None,АОЛ,,ФГУП ...,РОСС ...,55372-13,...,Без статуса,нет д...,Извещение о непригодности,,,3.1.АОЛ.0080.2016 Государственный эталон едини...,,,,
1,2,1173224227,02-К,,None,АОЛ,,ФГУП ...,РОСС ...,55372-13,...,Без статуса,нет д...,Извещение о непригодности,,,3.1.АОЛ.0080.2016 Государственный эталон едини...,,,,
2,3,1173224228,03-К,,None,АОЛ,,ФГУП ...,РОСС ...,55372-13,...,Без статуса,нет д...,Извещение о непригодности,,,3.1.АОЛ.0080.2016 Государственный эталон едини...,,,,
3,4,1173224229,04-К,,None,АОЛ,,ФГУП ...,РОСС ...,55372-13,...,Без статуса,нет д...,Извещение о непригодности,,,3.1.АОЛ.0080.2016 Государственный эталон едини...,,,,
4,5,1173224230,05-К,,None,АОЛ,,ФГУП ...,РОСС ...,55372-13,...,Без статуса,нет д...,Извещение о непригодности,,,3.1.АОЛ.0080.2016 Государственный эталон едини...,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5832,5833,135201421,131,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
5833,5834,135201422,84,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
5834,5835,135201423,17,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
5835,5836,135201424,85,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
5836,5837,135207371,08-К,P1454,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,55372-13,...,Периодическая,И-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,

In [22]:
def get_result_owner(Owner, m_title, ):
    keys = {'regkey': 'd37e5f9c2df49556a580b1c3dc8dcc7a',
        'omi_Owner_name':Owner,
        'mitypeTitle':m_title,
        'export_type': '2'}
    r = requests.get('http://731163-cj72200.tmweb.ru/vri/', params=keys)
    df = pd.DataFrame(r.json())
    return df

In [24]:
#Получаем данные по маи
m_name = ['МАИ','Московский авиационный институт']
df_mai=pd.DataFrame()
for i in  m_name:
    print(i)
    df_mai = pd.concat([df_mai, get_result_owner(i, 'Расход')], ignore_index=True)
display(df_mai)

МАИ
Московский авиационный институт

,id,vri_id,mi_number,mi_modification,mi_manufactureYear,mi_signCipher,mi_Owner_name,org_title,fsa_ral_regNumbers_regNumber,mitypeNumber,...,vriType,result_docnum,result_doc_type,additional_info,means_npe,means_uve,means_mieta,means_ses,means_mis,means_reagent
0,1,5089428,4983041,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,Нет д...,Извещение о непригодности,0000-106511_1,,,,,68266-17 Установки поверочные (№01);,
1,2,5089429,4974303,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,Нет д...,Извещение о непригодности,0000-106512_1,,,,,68266-17 Установки поверочные (№01);,
2,3,5089430,4974303,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,2584/...,Извещение о непригодности,0000-107993_1,,3.1.ZВЮ.0115.2012 ГЭЕ давления 1горазряда с ди...,,ГСО 10706-2015 СО СОСТАВА ИСКУССТВЕННОЙ ГАЗОВО...,68266-17 Установки поверочные (№01);,
3,4,5089431,4983041,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,2583/...,Извещение о непригодности,0000-107991_1,,3.1.ZВЮ.0115.2012 ГЭЕ давления 1горазряда с ди...,,ГСО 10706-2015 СО СОСТАВА ИСКУССТВЕННОЙ ГАЗОВО...,68266-17 Установки поверочные (№01);,
4,5,5130596,4997035,VT900A,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,Нет д...,Извещение о непригодности,0000-111025_1,,,,,68266-17 Установки поверочные (№01);,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,9996,1097775291,11-18...,Contr...,None,ВСР,,ООО &...,RA.RU...,38417-08,...,Без статуса,ВСР-М...,Извещение о непригодности,,,,,,,
19996,9997,1097775292,12-20...,Contr...,None,ВСР,,ООО &...,RA.RU...,38417-08,...,Без статуса,ВСР-М...,Извещение о непригодности,,,,,,,
19997,9998,1097777413,11-19...,Contr...,None,ВСР,,ООО &...,RA.RU...,38417-08,...,Без статуса,ВСР-М...,Извещение о непригодности,,,,,,,
19998,9999,1097794282,12-20...,Contr...,None,ВСР,,ООО &...,RA.RU...,38417-08,...,Без статуса,ВСР-М...,Извещение о непригодности,,,,,,,
19999,10000,1097794283,12-20...,Contr...,None,ВСР,,ООО &...,RA.RU...,38417-08,...,Без статуса,ВСР-М...,Извещение о непригодности,,,,,,,

In [ ]:
def get_result_owner(Owner, m_title, ):
    keys = {'regkey': 'd37e5f9c2df49556a580b1c3dc8dcc7a',
        'omi_Owner_name':Owner,
        'mitypeTitle':m_title,
        'export_type': '2'}
    r = requests.get('http://731163-cj72200.tmweb.ru/vri/', params=keys)
    df = pd.DataFrame(r.json())
    return df

,id,vri_id,mi_number,mi_modification,mi_manufactureYear,mi_signCipher,mi_Owner_name,org_title,fsa_ral_regNumbers_regNumber,mitypeNumber,...,vriType,result_docnum,result_doc_type,additional_info,means_npe,means_uve,means_mieta,means_ses,means_mis,means_reagent
243,244,51409603,M1520...,EL-FLOW,2015,ДШЛ,Госуд...,ОБЩЕС...,RA.RU...,25705-10,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,3.6.АПП.0003.2016 Эталон единицы объёмного рас...,,,,
244,245,51409604,M1721...,EL-FLOW,2017,ДШЛ,Госуд...,ОБЩЕС...,RA.RU...,64700-16,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,3.6.АПП.0003.2016 Эталон единицы объёмного рас...,,,,
251,252,208588841,M1520...,EL-FLOW,2015,ДШЛ,Федер...,ОБЩЕС...,RA.RU...,25705-10,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,,40432.09.1Р.00334741 40432-09 Стенд для калибр...,,,
252,253,208588842,M1721...,EL-FLOW,2017,ДШЛ,Федер...,ОБЩЕС...,RA.RU...,64700-16,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,,40432.09.1Р.00334741 40432-09 Стенд для калибр...,,,
895,896,427990440,M1721...,EL-FLOW,2017,ДШЛ,НИИ П...,ОБЩЕС...,RA.RU...,64700-16,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,,40432.09.1Р.00334741 40432-09 Стенд для калибр...,,,
896,897,427990506,M1520...,EL-FLOW,2015,ДШЛ,НИИ П...,ОБЩЕС...,RA.RU...,25705-10,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,,40432.09.1Р.00334741 40432-09 Стенд для калибр...,,,
897,898,427990539,M1721...,EL-FLOW,2017,ДШЛ,НИИ П...,ОБЩЕС...,RA.RU...,64700-16,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,,40432.09.1Р.00334741 40432-09 Стенд для калибр...,,,
898,899,427990697,M1520...,EL-FLOW,2015,ДШЛ,НИИ П...,ОБЩЕС...,RA.RU...,25705-10,...,Периодическая,C-ДШЛ...,Извещение о непригодности,,,,40432.09.1Р.00334741 40432-09 Стенд для калибр...,,,
963,964,95479072,156204,РСМ-0...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,19714-05,...,Периодическая,C-БЯ/...,Извещение о непригодности,Вас импульса 10 л/имп,,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
964,965,95479073,176064,РСМ-0...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,19714-05,...,Периодическая,C-БЯ/...,Извещение о непригодности,Вас импульса 10 л/имп,,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
987,988,172632977,161954,Питер...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-БЯ/...,Извещение о непригодности,"0,25 л/имп",,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
988,989,172632978,154478,Питер...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-БЯ/...,Извещение о непригодности,"0,25 л/имп",,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
989,990,172632979,153857,Питер...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-БЯ/...,Извещение о непригодности,"0,25 л/имп",,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
990,991,172632981,164427,Питер...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-БЯ/...,Извещение о непригодности,"0,25 л/имп",,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
991,992,172632983,154157,Питер...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-БЯ/...,Извещение о непригодности,"0,25 л/имп",,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
992,993,172632984,161095,Питер...,None,БЯ,МАИ+3Н,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-БЯ/...,Извещение о непригодности,"0,25 л/имп",,,53155.13.2Р.00163517 53155-13 Установки пролив...,,,
3256,3257,113812494,95190812,Карат...,None,ГФЕ,ООО &...,ФЕДЕР...,RA.RU...,44424-10,...,Периодическая,И-ГФЕ...,Извещение о непригодности,,,,19442.05.2Р.03001 19442-05 Установки стационар...,,,
5349,5350,298056858,735319,ЭРСВ-...,None,БГ,Индив...,ФЕДЕР...,RA.RU...,20293-05,...,Периодическая,C-БГ/...,Извещение о непригодности,,,3.1.ZБГ.0424.2021 Рабочий эталон единицы объем...,56478.14.4Р.00882837 56478-14 Частотомеры элек...,,,
5350,5351,298056859,735281,ЭРСВ-...,None,БГ,Индив...,ФЕДЕР...,RA.RU...,20293-05,...,Периодическая,C-БГ/...,Извещение о непригодности,,,3.1.ZБГ.0424.2021 Рабочий эталон единицы объем...,56478.14.4Р.00882837 56478-14 Частотомеры элек...,,,
6414,6415,268830019,42113214,25-Т1...,None,ВРК,Исмаи...,ОБЩЕС...,1462,44424-12,...,Первичная поверка,C-ВРК...,Извещение о непригодности,,,,56478.14.4Р.00770233 56478-14 Частотомеры элек...,,53505-13 Приборы комбинированные (№39516228/80...,
7397,7398,474434178,245251,Питер...,None,БИ,ИП Ба...,Федер...,RA.RU...,46814-11,...,Периодическая,C-БИ/...,Извещение о непригодности,,,3.1.ZБИ.0900.2021 Рабочий эталон единиц массов...,,,53505-13 Приборы комбинированные (№39509340/60...,
7398,7399,474434179,242693,Питер...,None,БИ,ИП Ба...,Федер...,RA.RU...,46814-11,...,Периодическая,C-БИ/...,Извещение о непригодности,,,3.1.ZБИ.0900.2021 Рабочий эталон единиц массов...,,,53505-13 Приборы комбинированные (№39509340/60...,
7700,7701,436087233,33831,мод. ...,None,АГ,МАНО ...,ФЕДЕР...,RA.RU...,46036-10,...,Периодическая,C-АГ/...,Извещение о непригодности,,,,32869.06.4Р.01289217 32869-06 Частотомеры элек...,,,
7791,7792,458359617,029464,Питер...,None,АС,Магом...,ФЕДЕР...,RA.RU...,46814-11,...,Периодическая,C-АС/...,Извещение о непригодности,,,,64632.16.3Р.00707083 64632-16 Установки поверо...,,,

In [25]:
def get_result_home(number):
    keys = {'regkey': 'd37e5f9c2df49556a580b1c3dc8dcc7a',
        'mi_number':number,
        'export_type': '2'}
    r = requests.get('http://731163-cj72200.tmweb.ru/vri/', params=keys)
    df = pd.DataFrame(r.json())
    return df

In [32]:
m_num = ['22-464875','22-332731']
df_home=pd.DataFrame()
for i in  m_num:
    print(i)
    df_home = pd.concat([df_home, get_result_home(i)], ignore_index=True)
display(df_home)

22-464875
22-332731

,id,vri_id,mi_number,mi_modification,mi_manufactureYear,mi_signCipher,mi_Owner_name,org_title,fsa_ral_regNumbers_regNumber,mitypeNumber,...,vriType,result_docnum,result_doc_type,additional_info,means_npe,means_uve,means_mieta,means_ses,means_mis,means_reagent
0,1,191984258,22-46...,WFW 2...,2022,ВИР,ООО &...,ОБЩЕС...,RA.RU...,54418-13,...,Первичная поверка,C-ВИР...,Извещение о непригодности,,,,48421.11.РЭ.94293 48421-11 Установка для повер...,,,
1,1,174199562,22-33...,WFK 2...,2022,ВИР,ООО &...,ОБЩЕС...,RA.RU...,54418-13,...,Первичная поверка,C-ВИР...,Извещение о непригодности,,,,48421.11.РЭ.94293 48421-11 Установка для повер...,,,

In [39]:
df_full = pd.concat([df_mai, df_tsagi], ignore_index=True)
display(df_full)

,id,vri_id,mi_number,mi_modification,mi_manufactureYear,mi_signCipher,mi_Owner_name,org_title,fsa_ral_regNumbers_regNumber,mitypeNumber,...,vriType,result_docnum,result_doc_type,additional_info,means_npe,means_uve,means_mieta,means_ses,means_mis,means_reagent
0,1,5089428,4983041,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,Нет д...,Извещение о непригодности,0000-106511_1,,,,,68266-17 Установки поверочные (№01);,
1,2,5089429,4974303,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,Нет д...,Извещение о непригодности,0000-106512_1,,,,,68266-17 Установки поверочные (№01);,
2,3,5089430,4974303,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,2584/...,Извещение о непригодности,0000-107993_1,,3.1.ZВЮ.0115.2012 ГЭЕ давления 1горазряда с ди...,,ГСО 10706-2015 СО СОСТАВА ИСКУССТВЕННОЙ ГАЗОВО...,68266-17 Установки поверочные (№01);,
3,4,5089431,4983041,VT650,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,2583/...,Извещение о непригодности,0000-107991_1,,3.1.ZВЮ.0115.2012 ГЭЕ давления 1горазряда с ди...,,ГСО 10706-2015 СО СОСТАВА ИСКУССТВЕННОЙ ГАЗОВО...,68266-17 Установки поверочные (№01);,
4,5,5130596,4997035,VT900A,None,ВЮ,,ФЕДЕР...,RA.RU...,76330-19,...,Без статуса,Нет д...,Извещение о непригодности,0000-111025_1,,,,,68266-17 Установки поверочные (№01);,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25832,5833,135201421,131,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
25833,5834,135201422,84,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
25834,5835,135201423,17,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
25835,5836,135201424,85,МТ (0...,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,3383-72,...,Периодическая,C-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,
25836,5837,135207371,08-К,P1454,None,АОЛ,ФГУП ...,ФЕДЕР...,РОСС ...,55372-13,...,Периодическая,И-АОЛ...,Извещение о непригодности,,,,16026.97.2Р.74146 16026-97 Манометры избыточно...,,,

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings('ignore')

# --- подготовка данных ---

# Источник (МАИ / ЦАГИ)
source_counts = pd.Series({'МАИ (расходомеры)': len(df_mai), 'ЦАГИ (манометры)': len(df_tsagi)})

# Тип поверки
vri_counts = df_full['vriType'].fillna('Не указан').value_counts()

# Топ-15 шифров знака (поверочные организации)
cipher_counts = df_full['mi_signCipher'].fillna('Не указан').value_counts().head(15)

# Тип результирующего документа
doc_counts = df_full['result_doc_type'].fillna('Не указан').value_counts()

# --- построение ---
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Анализ поверок средств измерения (МАИ + ЦАГИ)', fontsize=16, fontweight='bold', y=1.01)

# 1. Соотношение источников (pie)
ax = axes[0, 0]
ax.pie(source_counts, labels=source_counts.index, autopct='%1.1f%%',
       colors=['#4C72B0', '#DD8452'], startangle=90,
       wedgeprops={'edgecolor': 'white', 'linewidth': 2})
ax.set_title('Соотношение МАИ / ЦАГИ', fontsize=13, fontweight='bold')

# 2. Тип поверки (horizontal bar)
ax = axes[0, 1]
bars = ax.barh(vri_counts.index, vri_counts.values, color='#4C72B0', edgecolor='white')
ax.set_title('Распределение по типу поверки', fontsize=13, fontweight='bold')
ax.set_xlabel('Количество записей')
ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{int(x):,}'.replace(',', ' ')))
for bar, val in zip(bars, vri_counts.values):
    ax.text(bar.get_width() + max(vri_counts.values) * 0.01, bar.get_y() + bar.get_height() / 2,
            f'{val:,}'.replace(',', ' '), va='center', fontsize=9)
ax.margins(x=0.15)

# 3. Топ-15 шифров знака поверителя
ax = axes[1, 0]
bars = ax.barh(cipher_counts.index[::-1], cipher_counts.values[::-1], color='#DD8452', edgecolor='white')
ax.set_title('Топ-15 шифров поверителя (mi_signCipher)', fontsize=13, fontweight='bold')
ax.set_xlabel('Количество записей')
ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{int(x):,}'.replace(',', ' ')))
for bar, val in zip(bars, cipher_counts.values[::-1]):
    ax.text(bar.get_width() + max(cipher_counts.values) * 0.01, bar.get_y() + bar.get_height() / 2,
            f'{val:,}'.replace(',', ' '), va='center', fontsize=9)
ax.margins(x=0.2)

# 4. Тип результирующего документа
ax = axes[1, 1]
bars = ax.barh(doc_counts.index, doc_counts.values, color='#55A868', edgecolor='white')
ax.set_title('Тип результирующего документа', fontsize=13, fontweight='bold')
ax.set_xlabel('Количество записей')
ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{int(x):,}'.replace(',', ' ')))

# Перенос длинных меток
import textwrap
ax.set_yticklabels([textwrap.fill(lbl.get_text(), 28) for lbl in ax.get_yticklabels()])
for bar, val in zip(bars, doc_counts.values):
    ax.text(bar.get_width() + max(doc_counts.values) * 0.01, bar.get_y() + bar.get_height() / 2,
            f'{val:,}'.replace(',', ' '), va='center', fontsize=9)
ax.margins(x=0.2)

plt.tight_layout()
plt.savefig('vri_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print(f"\nВсего записей в df_full: {len(df_full):,}".replace(',', ' '))
print(f"Колонки ({len(df_full.columns)}): {list(df_full.columns)}")